version: '3'

services:
  python-web-app:
    build: ./app
    container_name: python-web-app
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - python-web-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
